version: 0.1.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: AypNsJQUSQWSGAENhnOkPD4RbcLQ0Y8BQ6Hhd8Kv7FNVsBU35eB6GxaZB/NcBxU3
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: iEc4MoxlFnOObwBuH2C2sixXpFP5OqVJosYv3GcTMrt0Oo20StvHW07CZ/Rrwnx4
  force_update: true
  on:
    branch: master
